server:
  port: 9999
  tomcat:
    basedir: /usr/local #配置临时目录

spring:
  application:
    name: nacos-provider-a
  redis:
    database: 0
    host: 192.168.2.11
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    timeout: 10000s





#配置swagger-ui 密码登陆
swagger:
  production: false
  basic:
    enable: true
    username: mqz
    password: mqz
  #自定义配置，是否开启swagger
  enabled: true
  info:
    title: 提供方-在线接口文档
    description: 蒙大拿
    url: http://localhost:9999/doc.html
    contact: https://github.com/DemoMeng
    version: 1.0


jwt:
  secret: Mars-Cloud
  key:
    userId: USER_ID
    token: TOKEN
    roleIdList: ROLE_ID_LIST








